version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD : root_secret
      MYSQL_DATABASE: spring_community
      MYSQL_USER: user
      MYSQL_PASSWORD : password
    ports:
      - "3306:3306"
    volumes:
      - spring_community:/var/lib/mysql

volumes:
  spring_community: